// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: vertex/vertex_query.proto

package vertex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VertexQueryService_Query_FullMethodName = "/vertex_query.VertexQueryService/Query"
)

// VertexQueryServiceClient is the client API for VertexQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VertexQueryServiceClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type vertexQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVertexQueryServiceClient(cc grpc.ClientConnInterface) VertexQueryServiceClient {
	return &vertexQueryServiceClient{cc}
}

func (c *vertexQueryServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, VertexQueryService_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VertexQueryServiceServer is the server API for VertexQueryService service.
// All implementations must embed UnimplementedVertexQueryServiceServer
// for forward compatibility
type VertexQueryServiceServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedVertexQueryServiceServer()
}

// UnimplementedVertexQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVertexQueryServiceServer struct {
}

func (UnimplementedVertexQueryServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedVertexQueryServiceServer) mustEmbedUnimplementedVertexQueryServiceServer() {}

// UnsafeVertexQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VertexQueryServiceServer will
// result in compilation errors.
type UnsafeVertexQueryServiceServer interface {
	mustEmbedUnimplementedVertexQueryServiceServer()
}

func RegisterVertexQueryServiceServer(s grpc.ServiceRegistrar, srv VertexQueryServiceServer) {
	s.RegisterService(&VertexQueryService_ServiceDesc, srv)
}

func _VertexQueryService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VertexQueryServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VertexQueryService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VertexQueryServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VertexQueryService_ServiceDesc is the grpc.ServiceDesc for VertexQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VertexQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vertex_query.VertexQueryService",
	HandlerType: (*VertexQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _VertexQueryService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vertex/vertex_query.proto",
}
